### ISSUE TITLE
关于涂抹之后如何擦出的问题

### ISSUE THREAD

**Issue by lazycoder417** [Mikora/CustomCamera#1]
你好，我想问下  就是我在涂抹之后  如何自己加一个橡皮擦 擦除掉之前涂抹的内容呢  我还是按照你之前涂抹的逻辑来实现的  但是发现虽然涂抹的路径在上面了 但是没有擦除掉以前的内容  希望能给说下原理  万分感谢

**Comment by huangcheng1** [comment]
@lazycoder417 这个后面我再更新一个库吧，然后应该会更简单一些

**Comment by huangcheng1** [comment]
@lazycoder417 看我独立的那个涂抹功能，同理可以做出模糊后擦除的功能

[https://github.com/huangcheng1/CTImageEdit](高斯涂抹)
